# Generated by Django 2.2 on 2019-07-22 09:14

import course.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('base', '0003_auto_20190722_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=1, max_length=128, verbose_name='课程名称')),
                ('detail', models.TextField(verbose_name='课程详情')),
                ('degree', models.IntegerField(choices=[(0, '无'), (1, '本科')], default=0, verbose_name='参考学历')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击数')),
                ('per', models.FloatField(verbose_name='完成的金币反馈率')),
                ('putaway_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上架时间')),
                ('poster', models.ImageField(blank=1, upload_to=course.models.get_uploadto, verbose_name='预览图')),
                ('require_course', models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='前置课程')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程树名称')),
                ('describe', models.TextField(verbose_name='课程树描述')),
            ],
            options={
                'verbose_name': '课程天赋',
                'verbose_name_plural': '课程天赋表',
            },
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(verbose_name='问题描述')),
                ('answer', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], verbose_name='问题答案')),
                ('course', models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='哪个课程的习题')),
                ('user', models.ManyToManyField(blank=1, to='user.User', verbose_name='完成习题的用户')),
            ],
            options={
                'verbose_name': '习题集',
                'verbose_name_plural': '习题表',
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='视频顺序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Video')),
            ],
            options={
                'db_table': 'course_video_relationship',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tree',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to='course.Tree', verbose_name='课程天赋树表'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(blank=1, to='user.User', verbose_name='完成课程的用户'),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.ManyToManyField(blank=1, through='course.CourseVideo', to='base.Video', verbose_name='包含视频'),
        ),
    ]
