# Generated by Django 2.2 on 2019-07-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190722_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
        migrations.AlterModelTable(
            name='coursevideo',
            table=None,
        ),
    ]
