# Generated by Django 2.2 on 2019-07-12 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='轮播图片')),
                ('url', models.CharField(max_length=200, verbose_name='链接地址')),
                ('putaway_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图表',
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(choices=[(0, '中文(简体)'), (1, 'English')], default=0, verbose_name='翻译语')),
                ('subtitle', models.FileField(upload_to='course/subtitle', verbose_name='字幕')),
                ('cost_coin', models.IntegerField(default=0, verbose_name='消费的金币')),
                ('click_count', models.IntegerField(default=0, verbose_name='字幕点击数')),
            ],
            options={
                'verbose_name': '视频字幕信息',
                'verbose_name_plural': '视频字幕表',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='视频名称')),
                ('poster', models.ImageField(blank=1, upload_to='', verbose_name='预览图')),
                ('url', models.URLField(blank=1, verbose_name='视频链接')),
                ('classify', models.IntegerField(choices=[(0, '教育'), (1, '娱乐')], default=0, verbose_name='视屏分类')),
                ('click_count', models.IntegerField(default=0, verbose_name='视频点击数')),
                ('desc', models.TextField(verbose_name='视频描述')),
                ('cost_coin', models.IntegerField(default=0, verbose_name='消费的金币')),
                ('putaway_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上架时间')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频表',
                'ordering': ['name'],
            },
        ),
    ]
