# Generated by Django 2.2 on 2019-07-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='buy_user',
            field=models.ManyToManyField(blank=1, related_name='v_buy_user', to='user.User', verbose_name='购买者'),
        ),
        migrations.AddField(
            model_name='video',
            name='putaway_user',
            field=models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, related_name='putaway_user', to='user.User', verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='buy_user',
            field=models.ManyToManyField(blank=1, related_name='s_buy_user', to='user.User', verbose_name='购买者'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='putaway_user',
            field=models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to='base.Video', verbose_name='视频'),
        ),
    ]
