# Generated by Django 2.2 on 2019-07-22 08:59

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190712_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
