# Generated by Django 2.2 on 2019-07-22 09:26

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190722_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
